### ISSUE TITLE
Error with Simple Upload Form

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#56]
Klicking on the "upload" button immediately shows the following error:

```
[ed2364dc32082e8ba59fc66e] /index.php?title=Spezial:Hochladefenster&pfInputID=input_31 TypeError: HTMLForm::__construct(): Argument #2 ($context) must be of type IContextSource, string given, called in /extensions/PageForms/specials/PF_UploadForm.php on line 45

Backtrace:

from includes/htmlform/HTMLForm.php(374)
#0 /extensions/PageForms/specials/PF_UploadForm.php(45): HTMLForm->__construct()
#1 /extensions/PageForms/specials/PF_UploadWindow.php(221): PFUploadForm->__construct()
#2 /extensions/PageForms/specials/PF_UploadWindow.php(179): PFUploadWindow->getUploadForm()
#3 /includes/specialpage/SpecialPage.php(701): PFUploadWindow->execute()
#4 /includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#5 /includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#6 /includes/MediaWiki.php(904): MediaWiki->performRequest()
#7 /includes/MediaWiki.php(562): MediaWiki->main()
#8 /index.php(50): MediaWiki->run()
#9 /index.php(46): wfIndexMain()
#10 {main}
```

Strangely (fortunaltely) this does not happen in all installations. Any idea what could be the cause?`
Am using latest master with MW 1.39.6.

**Comment by krabina** [comment]
Happens only if `$wgPageFormsSimpleUpload = false;`
The simple upload works.

**Comment by krabina** [comment]
@gesinn-it-gea so this is not fixed in 5.3.4.7

**Comment by krabina** [comment]
Thank you, I can confirm this is working now!
