### ISSUE TITLE
Red link to a file upload throws error: Call to a member function getExtensionData()

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#66]
When you add the link `[[Datei:test123.pdf]] on a page to a file that has not been uploaded, it will lead to the upload dialog of MediaWiki. 

With PF, you can define a form for additonal information to want to add to file pages. You can put this form, lets call it "Document" in the Project namespace with the parser function `{{#default_form:Document}}`

This way, PF will show on every wiki page in the File: namespace to let you enter additional data.

Now if you have a link to a not yet existing file like this
[[:File:test123.pdf]]
The form "Document" will be invoked (the red link wil point to` ..index.php?title=File:Test123.pdf&action=formedit&redlink=1`

When you click on the link, the following error is shown:

```
MediaWiki internal error.

Original exception: [6b16c5ac4536fe22cdf20a1a] /index.php?title=Datei:Test123.pdf&action=formedit&redlink=1 Error: Call to a member function getExtensionData() on bool
Backtrace:
from extensions/PageForms/includes/PF_FormEditAction.php(164)
#0 extensions/PageForms/includes/PF_FormEditAction.php(142): PFFormEditAction::handlePFDefaultFormOptions()
#1 includes/HookContainer/HookContainer.php(338): PFFormEditAction::displayTab()
#2 includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#3 includes/HookContainer/HookRunner.php(3543): MediaWiki\HookContainer\HookContainer->run()
#4 includes/skins/SkinTemplate.php(1203): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation__Universal()
#5 includes/skins/SkinTemplate.php(1574): SkinTemplate->runOnSkinTemplateNavigationHooks()
#6 includes/skins/SkinTemplate.php(790): SkinTemplate->buildContentNavigationUrlsInternal()
#7 includes/skins/SkinTemplate.php(762): SkinTemplate->getPortletsTemplateData()
#8 includes/skins/Skin.php(667): SkinTemplate->getCategoryLinks()
#9 includes/skins/SkinTemplate.php(259): Skin->getCategories()
#10 skins/Kma/src/Chameleon.php(113): SkinTemplate->prepareQuickTemplate()
#11 includes/skins/SkinTemplate.php(146): Skins\Chameleon\Chameleon->prepareQuickTemplate()
#12 includes/skins/SkinTemplate.php(177): SkinTemplate->generateHTML()
#13 includes/OutputPage.php(2876): SkinTemplate->outputPage()
#14 includes/MediaWiki.php(922): OutputPage->output()
#15 includes/MediaWiki.php(562): MediaWiki->main()
#16 index.php(50): MediaWiki->run()
#17 index.php(46): wfIndexMain()
#18 {main}

Exception caught inside exception handler: [6b16c5ac4536fe22cdf20a1a] /index.php?title=Datei:Test123.pdf&action=formedit&redlink=1 Error: Call to a member function getExtensionData() on bool
Backtrace:
from extensions/PageForms/includes/PF_FormEditAction.php(164)
#0 extensions/PageForms/includes/PF_FormEditAction.php(142): PFFormEditAction::handlePFDefaultFormOptions()
#1 includes/HookContainer/HookContainer.php(338): PFFormEditAction::displayTab()
#2 includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#3 includes/HookContainer/HookRunner.php(3543): MediaWiki\HookContainer\HookContainer->run()
#4 includes/skins/SkinTemplate.php(1203): MediaWiki\HookContainer\HookRunner->onSkinTemplateNavigation__Universal()
#5 includes/skins/SkinTemplate.php(1574): SkinTemplate->runOnSkinTemplateNavigationHooks()
#6 includes/skins/SkinTemplate.php(790): SkinTemplate->buildContentNavigationUrlsInternal()
#7 includes/skins/SkinTemplate.php(762): SkinTemplate->getPortletsTemplateData()
#8 includes/skins/Skin.php(667): SkinTemplate->getCategoryLinks()
#9 includes/skins/SkinTemplate.php(259): Skin->getCategories()
#10 skins/Kma/src/Chameleon.php(113): SkinTemplate->prepareQuickTemplate()
#11 includes/skins/SkinTemplate.php(146): Skins\Chameleon\Chameleon->prepareQuickTemplate()
#12 includes/skins/SkinTemplate.php(177): SkinTemplate->generateHTML()
#13 includes/OutputPage.php(2876): SkinTemplate->outputPage()
#14 includes/exception/MWExceptionRenderer.php(183): OutputPage->output()
#15 includes/exception/MWExceptionRenderer.php(102): MWExceptionRenderer::reportHTML()
#16 includes/exception/MWExceptionHandler.php(131): MWExceptionRenderer::output()
#17 includes/exception/MWExceptionHandler.php(248): MWExceptionHandler::report()
#18 includes/MediaWiki.php(584): MWExceptionHandler::handleException()
#19 index.php(50): MediaWiki->run()
#20 index.php(46): wfIndexMain()
#21 {main}

```

Am using PF 5.3.4.8, MedaiWiki 1.39.6

**Comment by krabina** [comment]
This is solved in master
