### ISSUE TITLE
Error: Call to a member function isDeleted() on null on clicking on upload file in multiple-instance template

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-PageForms#80]
In a mulitple instance template, an uploadable file leads to the following error when clickin on "upload":

```
from extensions/PageForms/specials/PF_UploadWindow.php(320)
#0 /extensions/PageForms/specials/PF_UploadWindow.php(261): PFUploadWindow->showViewDeletedLinks()
#1/extensions/PageForms/specials/PF_UploadWindow.php(244): PFUploadWindow->showUploadForm()
#2 /includes/specialpage/SpecialPage.php(701): PFUploadWindow->execute()
#3 includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#4 /includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#5 includes/MediaWiki.php(904): MediaWiki->performRequest()
#6 /includes/MediaWiki.php(562): MediaWiki->main()
#7 /index.php(50): MediaWiki->run()
#8 /index.php(46): wfIndexMain()
#9 {main}
```

`{{{field|Unterlagen|holds template}}}`

```
{{{for template|Unterlage|multiple|add button text=Unterlage hinzufügen|embed in field=Aktuelles[Unterlagen]}}}
<div class="form-group row" >
<div class="col-sm-2">{{{field|Unterlagentyp|input type=dropdown|values=Datei,Link|default=Datei|show on select=Datei=>DATEI;Link=>LINK|class=form-control}}}</div>
</div>
<div class="form-group row" id="DATEI">
<div class="col-sm-2 col-form-label">Datei</div>
<div class="col-sm-10" id="DATEI">{{{field|Datei|uploadable|class=form-control}}}</div>
<div class="col-sm-2 col-form-label">Bezeichnung</div>
<div class="col-sm-10">{{{field|Dateiname|input type=text|placeholder=optional|class=form-control}}}</div>
</div>
<div class="form-group row" id="LINK">
<div class="col-sm-2 col-form-label">Link</div>
<div class="col-sm-10">{{{field|Link|input type=text|class=form-control}}}</div>
<div class="col-sm-2 col-form-label">Bezeichnung</div>
<div class="col-sm-10">{{{field|Linkname|input type=text|class=form-control}}}</div>
</div>

{{{end template}}}
```

**Comment by krabina** [comment]
Versions:
Software|Version
-- | --
[MediaWiki](https://www.mediawiki.org/) 	 |1.39.10
[PHP](https://php.net/) 	|7.4.3-4ubuntu2.28 (fpm-fcgi)
[MariaDB](https://mariadb.org/) 	|10.3.39-MariaDB-0ubuntu0.20.04.2
[ICU](https://icu.unicode.org/) |	66.1
[Elasticsearch](https://www.elastic.co/elasticsearch) 	|7.10.2
[Page Forms](https://www.mediawiki.org/wiki/Extension:Page_Forms)	 |5.3.4.8 (70c3c8a) 10:52, 10. Dez. 2024
